version: '3.8'

services:
  vpn-bot:
    build: .
    container_name: vpn-telegram-bot
    restart: unless-stopped
    volumes:
      - bot-data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - XUI_PANEL_URL=${XUI_PANEL_URL}
      - XUI_USERNAME=${XUI_USERNAME}
      - XUI_PASSWORD=${XUI_PASSWORD}
      - INBOUND_ID=${INBOUND_ID}
      - DATA_LIMIT_GB=${DATA_LIMIT_GB}

volumes:
  bot-data: