version: '3.8'

services:
  fastapi:
    build: .
    container_name: vpn-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  bot:
    build: .
    container_name: vpn-telegram-bot
    command: python bot/bot.py
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: vpn-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vpn
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
